# Generated by Django 2.2.7 on 2020-02-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessReport',
            fields=[
                ('successreport_id', models.AutoField(primary_key=True, serialize=False)),
                ('auctiondetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.AuctionDetails')),
                ('currentbid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Auction.CurrentBid')),
            ],
        ),
        migrations.CreateModel(
            name='CancelReport',
            fields=[
                ('cancelreport_id', models.AutoField(primary_key=True, serialize=False)),
                ('cancelreport_date', models.DateTimeField()),
                ('cancelreport_reason', models.TextField()),
                ('auctiondetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auction.AuctionDetails')),
            ],
        ),
        migrations.CreateModel(
            name='AuctionQuery',
            fields=[
                ('auctionquery_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_query', models.TextField()),
                ('successreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.SuccessReport')),
            ],
        ),
    ]
