# Generated by Django 2.2.7 on 2020-02-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=36)),
                ('user_username', models.CharField(max_length=36)),
                ('user_password', models.CharField(max_length=36)),
                ('user_confirm_password', models.CharField(max_length=36)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('idproof_images', models.ImageField(upload_to='idproof/')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.Country')),
                ('idproof', models.ManyToManyField(to='Admin.IdProof')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.State')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('messages_id', models.AutoField(primary_key=True, serialize=False)),
                ('messages_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
        ),
    ]
